#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Text.Json.Nodes;

namespace Microsoft.Dafny;

public static class ResolvedAstJsonSerializer {
  public static JsonObject Serialize(Program program) {
    return new Serializer().Serialize(program);
  }

  private sealed class Serializer {
    public JsonObject Serialize(Program program) {
      return new JsonObject {
        ["format"] = "dafny-resolved-ast",
        ["version"] = 1,
        ["resolved"] = true,
        ["programName"] = program.Name,
        ["root"] = SerializeNode(program, new HashSet<INode>(NodeReferenceComparer.Instance))
      };
    }

    private JsonObject SerializeNode(INode node, ISet<INode> visited) {
      if (!visited.Add(node)) {
        return CreateSharedNode(node);
      }

      return node switch {
        Program program => EmitProgram(program, visited),
        LiteralModuleDecl literalModuleDecl => EmitModule(literalModuleDecl.ModuleDef, visited),
        ModuleDefinition moduleDefinition => EmitModule(moduleDefinition, visited),
        DefaultClassDecl defaultClassDecl => EmitDefaultClass(defaultClassDecl, visited),
        TopLevelDeclWithMembers topLevelDeclWithMembers => EmitTopLevelDeclWithMembers(topLevelDeclWithMembers, visited),
        Function function => EmitFunction(function, visited),
        Method method => EmitMethod(method, visited),
        Formal formal => EmitFormal(formal, visited),
        BlockStmt blockStmt => EmitBlock(blockStmt, visited),
        IfStmt ifStmt => EmitIf(ifStmt, visited),
        AssertStmt assertStmt => EmitAssert(assertStmt, visited),
        VarDeclStmt varDeclStmt => EmitVarDecl(varDeclStmt, visited),
        LocalVariable localVariable => EmitLocalVariable(localVariable),
        AssignStatement assignStatement => EmitAssign(assignStatement, visited),
        SingleAssignStmt singleAssignStmt => EmitSingleAssign(singleAssignStmt, visited),
        ExprRhs exprRhs => EmitAssignmentRhs(exprRhs, visited),
        CallStmt callStmt => EmitCall(callStmt, visited),
        FunctionCallExpr functionCallExpr => EmitFunctionCall(functionCallExpr, visited),
        MemberSelectExpr memberSelectExpr => EmitMemberSelect(memberSelectExpr, visited),
        BinaryExpr binaryExpr => EmitBinary(binaryExpr, visited),
        NegationExpression negationExpression => EmitNegation(negationExpression, visited),
        UnaryOpExpr unaryOpExpr => EmitUnary(unaryOpExpr, visited),
        SetDisplayExpr setDisplayExpr => EmitSetDisplay(setDisplayExpr, visited),
        IdentifierExpr identifierExpr => EmitIdentifier(identifierExpr),
        LiteralExpr literalExpr => EmitLiteral(literalExpr),
        NameSegment nameSegment => EmitNameSegment(nameSegment),
        UserDefinedType userDefinedType => EmitUserDefinedType(userDefinedType),
        Specification<Expression> specification => EmitSpecification(specification, visited),
        Specification<FrameExpression> specification => EmitSpecification(specification, visited),
        AttributedExpression attributedExpression => SerializeNode(attributedExpression.E, visited),
        AutoGeneratedExpression autoGeneratedExpression => SerializeNode(autoGeneratedExpression.E, visited),
        ApplySuffix applySuffix when applySuffix.ResolvedExpression != null => SerializeNode(applySuffix.ResolvedExpression, visited),
        _ => EmitFallback(node, visited)
      };
    }

    private JsonObject EmitProgram(Program program, ISet<INode> visited) {
      var result = CreateNode(program);
      result["name"] = program.Name;
      AddNodes(result, "modules", program.Children, visited);
      return result;
    }

    private JsonObject EmitModule(ModuleDefinition moduleDefinition, ISet<INode> visited) {
      var result = CreateNode(moduleDefinition, kind: "module");
      AddLocation(result, moduleDefinition);
      if (moduleDefinition.Name is not "_module") {
        AddString(result, "name", moduleDefinition.Name);
      }

      AddNodes(result, "members", moduleDefinition.DefaultClass?.Members ?? Enumerable.Empty<MemberDecl>(), visited);
      AddNodes(result, "declarations", moduleDefinition.TopLevelDecls.Where(declaration => declaration is not DefaultClassDecl), visited);
      return result;
    }

    private JsonObject EmitDefaultClass(DefaultClassDecl defaultClassDecl, ISet<INode> visited) {
      var result = CreateNode(defaultClassDecl, kind: "default_class");
      AddLocation(result, defaultClassDecl);
      AddString(result, "name", defaultClassDecl.Name);
      AddNodes(result, "members", defaultClassDecl.Members, visited);
      return result;
    }

    private JsonObject EmitTopLevelDeclWithMembers(TopLevelDeclWithMembers declaration, ISet<INode> visited) {
      var result = CreateNode(declaration);
      AddLocation(result, declaration);
      AddString(result, "name", declaration.Name);
      AddStrings(result, "typeParameters", declaration.TypeArgs.Select(typeParameter => typeParameter.Name));
      AddTypes(result, "traits", declaration.Traits);
      AddNodes(result, "members", declaration.Members, visited);
      return result;
    }

    private JsonObject EmitFunction(Function function, ISet<INode> visited) {
      var result = CreateNode(function, kind: "function");
      AddLocation(result, function);
      AddString(result, "name", function.Name);
      AddStrings(result, "typeParameters", function.TypeArgs.Select(typeParameter => typeParameter.Name));
      AddNodes(result, "parameters", function.Ins, visited);
      AddType(result, "type", function.ResultType);
      AddNodes(result, "requires", function.Req.Select(requirement => requirement.E), visited);
      AddNodes(result, "ensures", function.Ens.Select(ensure => ensure.E), visited);
      AddNodes(result, "reads", function.Reads.Expressions ?? Enumerable.Empty<FrameExpression>(), visited);
      AddNodes(result, "decreases", function.Decreases.Expressions ?? Enumerable.Empty<Expression>(), visited);
      AddNode(result, "body", function.Body, visited);
      AddNode(result, "byMethodBody", function.ByMethodBody, visited);
      return result;
    }

    private JsonObject EmitMethod(Method method, ISet<INode> visited) {
      var result = CreateNode(method, kind: "method");
      AddLocation(result, method);
      AddString(result, "name", method.Name);
      AddStrings(result, "typeParameters", method.TypeArgs.Select(typeParameter => typeParameter.Name));
      AddNodes(result, "parameters", method.Ins, visited);
      AddNodes(result, "returns", method.Outs, visited);
      AddNodes(result, "requires", method.Req.Select(requirement => requirement.E), visited);
      AddNodes(result, "ensures", method.Ens.Select(ensure => ensure.E), visited);
      AddNodes(result, "reads", method.Reads.Expressions ?? Enumerable.Empty<FrameExpression>(), visited);
      AddNodes(result, "modifies", method.Mod.Expressions ?? Enumerable.Empty<FrameExpression>(), visited);
      AddNodes(result, "decreases", method.Decreases.Expressions ?? Enumerable.Empty<Expression>(), visited);
      AddNode(result, "body", method.Body, visited);
      return result;
    }

    private JsonObject EmitFormal(Formal formal, ISet<INode> visited) {
      var result = CreateNode(formal, kind: formal.InParam ? "parameter" : "return_parameter");
      AddString(result, "name", formal.Name);
      AddString(result, "parameterKind", formal.InParam ? "in" : "out");
      AddType(result, "type", formal.SyntacticType ?? formal.Type);
      AddNode(result, "defaultValue", formal.DefaultValue, visited);
      return result;
    }

    private JsonObject EmitBlock(BlockStmt blockStmt, ISet<INode> visited) {
      var result = CreateNode(blockStmt, kind: "block");
      AddNodes(result, "statements", blockStmt.Body, visited);
      return result;
    }

    private JsonObject EmitIf(IfStmt ifStmt, ISet<INode> visited) {
      var result = CreateNode(ifStmt, kind: "if");
      AddNode(result, "condition", ifStmt.Guard, visited);
      AddNode(result, "then", ifStmt.Thn, visited);
      AddNode(result, "else", ifStmt.Els, visited);
      return result;
    }

    private JsonObject EmitAssert(AssertStmt assertStmt, ISet<INode> visited) {
      var result = CreateNode(assertStmt, kind: "assert");
      AddNode(result, "condition", assertStmt.Expr, visited);
      return result;
    }

    private JsonObject EmitVarDecl(VarDeclStmt varDeclStmt, ISet<INode> visited) {
      var result = CreateNode(varDeclStmt, kind: "var_decl");
      AddNodes(result, "locals", varDeclStmt.Locals, visited);
      AddNode(result, "initializer", varDeclStmt.Assign, visited);
      return result;
    }

    private JsonObject EmitLocalVariable(LocalVariable localVariable) {
      var result = CreateNode(localVariable, kind: "local_variable");
      AddString(result, "name", localVariable.Name);
      AddType(result, "type", localVariable.type ?? localVariable.SyntacticType);
      if (localVariable.SyntacticType == null && localVariable.type != null) {
        result["typeSource"] = "inferred";
      }
      return result;
    }

    private JsonObject EmitAssign(AssignStatement assignStatement, ISet<INode> visited) {
      if (assignStatement.ResolvedStatements is { Count: 1 }) {
        return SerializeNode(assignStatement.ResolvedStatements[0], visited);
      }

      var result = CreateNode(assignStatement, kind: "assign");
      if (assignStatement.ResolvedStatements is { Count: > 0 } resolvedStatements) {
        AddNodes(result, "statements", resolvedStatements, visited);
      } else {
        AddNodes(result, "lhs", assignStatement.Lhss, visited);
        AddNodes(result, "rhs", assignStatement.Rhss, visited);
      }
      return result;
    }

    private JsonObject EmitSingleAssign(SingleAssignStmt singleAssignStmt, ISet<INode> visited) {
      var result = CreateNode(singleAssignStmt, kind: "assign");
      AddNode(result, "lhs", singleAssignStmt.Lhs, visited);
      AddNode(result, "rhs", singleAssignStmt.Rhs, visited);
      return result;
    }

    private JsonObject EmitAssignmentRhs(ExprRhs exprRhs, ISet<INode> visited) {
      return SerializeNode(exprRhs.Expr, visited);
    }

    private JsonObject EmitCall(CallStmt callStmt, ISet<INode> visited) {
      var result = CreateNode(callStmt, kind: "call");
      AddNodes(result, "results", callStmt.Lhs, visited);
      if (callStmt.Receiver is not StaticReceiverExpr) {
        AddNode(result, "receiver", callStmt.Receiver, visited);
      }
      AddString(result, "method", callStmt.MethodSelect.MemberName);
      AddNodes(result, "arguments", callStmt.Args, visited);
      return result;
    }

    private JsonObject EmitFunctionCall(FunctionCallExpr functionCallExpr, ISet<INode> visited) {
      var result = CreateNode(functionCallExpr, kind: "call");
      AddString(result, "name", functionCallExpr.Name);
      if (functionCallExpr.Receiver is not StaticReceiverExpr) {
        AddNode(result, "receiver", functionCallExpr.Receiver, visited);
      }
      AddNodes(result, "arguments", functionCallExpr.Args, visited);
      return result;
    }

    private JsonObject EmitMemberSelect(MemberSelectExpr memberSelectExpr, ISet<INode> visited) {
      var result = CreateNode(memberSelectExpr, kind: "member_access");
      AddString(result, "member", memberSelectExpr.MemberName);
      if (memberSelectExpr.Obj is not StaticReceiverExpr) {
        AddNode(result, "receiver", memberSelectExpr.Obj, visited);
      }
      return result;
    }

    private JsonObject EmitBinary(BinaryExpr binaryExpr, ISet<INode> visited) {
      var result = CreateNode(binaryExpr, kind: "binary");
      result["operator"] = BinaryExpr.OpcodeString(binaryExpr.Op);
      AddNode(result, "left", binaryExpr.E0, visited);
      AddNode(result, "right", binaryExpr.E1, visited);
      return result;
    }

    private JsonObject EmitNegation(NegationExpression negationExpression, ISet<INode> visited) {
      var result = CreateNode(negationExpression, kind: "negation");
      result["operator"] = "-";
      AddNode(result, "operand", negationExpression.E, visited);
      return result;
    }

    private JsonObject EmitUnary(UnaryOpExpr unaryOpExpr, ISet<INode> visited) {
      var result = CreateNode(unaryOpExpr, kind: "unary");
      result["operator"] = unaryOpExpr.Op.ToString();
      AddNode(result, "operand", unaryOpExpr.E, visited);
      return result;
    }

    private JsonObject EmitSetDisplay(SetDisplayExpr setDisplayExpr, ISet<INode> visited) {
      var result = CreateNode(setDisplayExpr, kind: setDisplayExpr.Finite ? "set" : "iset");
      AddNodes(result, "elements", setDisplayExpr.Elements, visited);
      return result;
    }

    private JsonObject EmitIdentifier(IdentifierExpr identifierExpr) {
      var result = CreateNode(identifierExpr, kind: "identifier");
      AddString(result, "name", identifierExpr.Name);
      return result;
    }

    private JsonObject EmitLiteral(LiteralExpr literalExpr) {
      var result = CreateNode(literalExpr, kind: GetLiteralKind(literalExpr));
      var value = SerializeLiteralValue(literalExpr.Value);
      if (value != null) {
        result["value"] = value;
      }
      return result;
    }

    private JsonObject EmitNameSegment(NameSegment nameSegment) {
      var result = CreateNode(nameSegment, kind: "name");
      AddString(result, "name", nameSegment.Name);
      AddTypes(result, "typeArguments", nameSegment.OptTypeArguments);
      return result;
    }

    private JsonObject EmitUserDefinedType(UserDefinedType userDefinedType) {
      var result = CreateNode(userDefinedType, kind: "user_defined_type");
      AddString(result, "name", userDefinedType.Name);
      AddTypes(result, "typeArguments", userDefinedType.TypeArgs);
      return result;
    }

    private JsonObject EmitSpecification<T>(Specification<T> specification, ISet<INode> visited) where T : Node {
      var result = CreateNode(specification, kind: "specification");
      AddNodes(result, "expressions", specification.Expressions ?? Enumerable.Empty<T>(), visited);
      return result;
    }

    private JsonObject EmitFallback(INode node, ISet<INode> visited) {
      var result = CreateNode(node);

      var value = GetFallbackValue(node);
      if (value != null) {
        result["value"] = value;
      }

      AddNodes(result, "children", node.Children.Where(ShouldIncludeChild), visited);
      return result;
    }

    private void AddLocation(JsonObject target, INode node) {
      var token = GetLocationToken(node, new HashSet<INode>(NodeReferenceComparer.Instance));
      if (token == null) {
        return;
      }

      target["location"] = new JsonObject {
        ["file"] = token.filename,
        ["line"] = token.line,
        ["column"] = token.col
      };
    }

    private static Token? GetLocationToken(INode? node, ISet<INode> visited) {
      if (node == null || !visited.Add(node)) {
        return null;
      }

      var token = node.ReportingRange.StartToken;
      if (HasUsableLocation(token)) {
        return token;
      }

      foreach (var child in node.Children) {
        var childToken = GetLocationToken(child, visited);
        if (childToken != null) {
          return childToken;
        }
      }

      return null;
    }

    private static bool HasUsableLocation(Token token) {
      return token != null && token.line > 0 && token.col > 0 && token.filename != null;
    }

    private JsonObject CreateSharedNode(INode node) {
      var result = CreateNode(node);
      result["shared"] = true;

      var value = GetFallbackValue(node);
      if (value != null) {
        result["value"] = value;
      }

      return result;
    }

    private JsonObject CreateNode(INode node, string? kind = null) {
      var result = new JsonObject {
        ["kind"] = kind ?? GetKind(node)
      };

      var type = GetNodeType(node);
      if (type != null) {
        result["type"] = type;
      }

      return result;
    }

    private static bool ShouldIncludeChild(INode child) {
      return child is not Name;
    }

    private static string GetKind(INode node) {
      if (TryGetStringProperty(node, "WhatKind") is { Length: > 0 } whatKind) {
        return NormalizeKind(whatKind) switch {
          "module_definition" => "module",
          _ => NormalizeKind(whatKind)
        };
      }

      return node switch {
        Name => "name",
        IdentifierExpr => "identifier",
        LiteralExpr literalExpr => GetLiteralKind(literalExpr),
        BinaryExpr => "binary",
        FunctionCallExpr => "call",
        MemberSelectExpr => "member_access",
        Statement => NormalizeTypeName(node.GetType().Name, "Stmt", "Statement"),
        _ => NormalizeTypeName(node.GetType().Name, "Expr", "Expression", "Decl")
      };
    }

    private static JsonNode? GetFallbackValue(INode node) {
      return node switch {
        Name name => JsonValue.Create(name.Value),
        ModuleDefinition moduleDefinition => GetStringValue(moduleDefinition.Name),
        Declaration declaration => GetStringValue(declaration.Name),
        IdentifierExpr identifierExpr => JsonValue.Create(identifierExpr.Name),
        MemberSelectExpr memberSelectExpr => JsonValue.Create(memberSelectExpr.MemberName),
        FunctionCallExpr functionCallExpr => JsonValue.Create(functionCallExpr.Name),
        BinaryExpr binaryExpr => JsonValue.Create(BinaryExpr.OpcodeString(binaryExpr.Op)),
        _ => GetStringValue(TryGetStringProperty(node, "Name")) ??
             GetStringValue(TryGetStringProperty(node, "DafnyName"))
      };
    }

    private static JsonNode? GetNodeType(INode node) {
      return node is Expression expression && expression.WasResolved() && expression.Type != null
        ? SerializeType(expression.Type)
        : null;
    }

    private static JsonNode? SerializeType(Type? type) {
      if (type == null) {
        return null;
      }

      var normalized = type.Normalize();
      return normalized switch {
        BoolType => TypeNode("bool"),
        CharType => TypeNode("char"),
        IntType => TypeNode("int"),
        RealType => TypeNode("real"),
        Fp64Type => TypeNode("fp64"),
        BigOrdinalType => TypeNode("big_ordinal"),
        FieldType => TypeNode("field"),
        BitvectorType bitvectorType => new JsonObject {
          ["kind"] = "bitvector",
          ["width"] = bitvectorType.Width
        },
        SeqType seqType => new JsonObject {
          ["kind"] = "seq",
          ["element"] = SerializeType(seqType.Arg)
        },
        SetType setType => new JsonObject {
          ["kind"] = setType.Finite ? "set" : "iset",
          ["element"] = SerializeType(setType.Arg)
        },
        MultiSetType multiSetType => new JsonObject {
          ["kind"] = "multiset",
          ["element"] = SerializeType(multiSetType.Arg)
        },
        MapType mapType => new JsonObject {
          ["kind"] = mapType.Finite ? "map" : "imap",
          ["key"] = SerializeType(mapType.Domain),
          ["value"] = SerializeType(mapType.Range)
        },
        ArrowType arrowType => SerializeArrowType(arrowType),
        UserDefinedType { ResolvedClass: TypeParameter typeParameter } => new JsonObject {
          ["kind"] = "type_parameter",
          ["name"] = typeParameter.Name
        },
        UserDefinedType userDefinedType => SerializeNamedType(userDefinedType),
        TypeProxy => TypeNode("proxy"),
        _ => new JsonObject {
          ["kind"] = "named",
          ["name"] = normalized.ToString()
        }
      };
    }

    private static JsonObject SerializeArrowType(ArrowType arrowType) {
      var result = new JsonObject {
        ["kind"] = "arrow",
        ["parameters"] = new JsonArray(arrowType.Args.Select(SerializeType).ToArray()),
        ["result"] = SerializeType(arrowType.Result)
      };

      if (ArrowType.IsPartialArrowTypeName(arrowType.Name)) {
        result["arrowKind"] = "partial";
      } else if (ArrowType.IsTotalArrowTypeName(arrowType.Name)) {
        result["arrowKind"] = "total";
      }

      return result;
    }

    private static JsonObject SerializeNamedType(UserDefinedType userDefinedType) {
      var result = new JsonObject {
        ["kind"] = "named"
      };

      var name = userDefinedType.Name;
      if (name.EndsWith("?", StringComparison.Ordinal)) {
        result["nullable"] = true;
        name = name[..^1];
      }

      result["name"] = name;
      if (userDefinedType.TypeArgs.Count > 0) {
        result["args"] = new JsonArray(userDefinedType.TypeArgs.Select(SerializeType).ToArray());
      }

      return result;
    }

    private static JsonObject TypeNode(string kind) {
      return new JsonObject {
        ["kind"] = kind
      };
    }

    private static JsonNode? SerializeLiteralValue(object? value) {
      return value switch {
        null => null,
        bool boolean => JsonValue.Create(boolean),
        BigInteger integer => JsonValue.Create(integer.ToString()),
        string text => JsonValue.Create(text),
        Microsoft.BaseTypes.BigDec decimalValue => JsonValue.Create(decimalValue.ToString()),
        _ => JsonValue.Create(value.ToString())
      };
    }

    private JsonNode SerializeChild(INode node, ISet<INode> visited) {
      return SerializeNode(node, visited);
    }

    private void AddNode(JsonObject target, string propertyName, INode? node, ISet<INode> visited) {
      if (node != null) {
        target[propertyName] = SerializeChild(node, visited);
      }
    }

    private void AddNodes(JsonObject target, string propertyName, IEnumerable<INode> nodes, ISet<INode> visited) {
      var serializedNodes = nodes.Select(node => SerializeChild(node, visited)).ToArray();
      if (serializedNodes.Length > 0) {
        target[propertyName] = new JsonArray(serializedNodes);
      }
    }

    private static void AddString(JsonObject target, string propertyName, string? value) {
      if (!string.IsNullOrEmpty(value)) {
        target[propertyName] = value;
      }
    }

    private static void AddStrings(JsonObject target, string propertyName, IEnumerable<string> values) {
      var items = new List<JsonNode?>();
      foreach (var value in values) {
        if (!string.IsNullOrEmpty(value)) {
          items.Add(JsonValue.Create(value));
        }
      }
      if (items.Count > 0) {
        target[propertyName] = new JsonArray(items.ToArray());
      }
    }

    private static void AddType(JsonObject target, string propertyName, Type? type) {
      var serialized = SerializeType(type);
      if (serialized != null) {
        target[propertyName] = serialized;
      }
    }

    private static void AddTypes(JsonObject target, string propertyName, IEnumerable<Type>? types) {
      if (types == null) {
        return;
      }

      var items = new List<JsonNode?>();
      foreach (var type in types) {
        var serialized = SerializeType(type);
        if (serialized != null) {
          items.Add(serialized);
        }
      }
      if (items.Count > 0) {
        target[propertyName] = new JsonArray(items.ToArray());
      }
    }

    private static JsonNode? GetStringValue(string? value) {
      return value == null ? null : JsonValue.Create(value);
    }

    private static string GetLiteralKind(LiteralExpr literalExpr) {
      return literalExpr switch {
        StringLiteralExpr => "literal.string",
        CharLiteralExpr => "literal.char",
        DecimalLiteralExpr => "literal.real",
        _ => literalExpr.Value switch {
          null => "literal.null",
          bool => "literal.bool",
          BigInteger => "literal.int",
          Microsoft.BaseTypes.BigDec => "literal.real",
          string => "literal.string",
          _ => "literal"
        }
      };
    }

    private static string NormalizeKind(string value) {
      return value.Trim().ToLowerInvariant().Replace(' ', '_');
    }

    private static string NormalizeTypeName(string typeName, params string[] suffixes) {
      var result = typeName;
      foreach (var suffix in suffixes) {
        if (result.EndsWith(suffix, StringComparison.Ordinal)) {
          result = result[..^suffix.Length];
          break;
        }
      }

      return ToSnakeCase(result);
    }

    private static string ToSnakeCase(string value) {
      if (string.IsNullOrEmpty(value)) {
        return value;
      }

      var characters = new List<char>(value.Length * 2) { char.ToLowerInvariant(value[0]) };
      for (var index = 1; index < value.Length; index++) {
        var current = value[index];
        if (char.IsUpper(current) && (char.IsLower(value[index - 1]) || (index + 1 < value.Length && char.IsLower(value[index + 1])))) {
          characters.Add('_');
        }
        characters.Add(char.ToLowerInvariant(current));
      }

      return new string(characters.ToArray());
    }

    private static string? TryGetStringProperty(object value, string propertyName) {
      var property = value.GetType().GetProperty(propertyName);
      if (property?.PropertyType != typeof(string) || property.GetMethod == null || property.GetIndexParameters().Length != 0) {
        return null;
      }

      try {
        return (string?)property.GetValue(value);
      } catch {
        return null;
      }
    }
  }

  private sealed class NodeReferenceComparer : IEqualityComparer<INode> {
    public static readonly NodeReferenceComparer Instance = new();

    public bool Equals(INode? x, INode? y) {
      return ReferenceEquals(x, y);
    }

    public int GetHashCode(INode obj) {
      return RuntimeHelpers.GetHashCode(obj);
    }
  }
}
